### ISSUE TITLE
add Usage instructions to README.md

### ISSUE THREAD

**Issue by bxparks** [hsaturn/EspMock#2]
@hsaturn: Please take a look at the updated README.md if you haven't already seen it. And I updated https://github.com/bxparks/EpoxyDuino#LibrariesAndMocks subsection to reference this project.

I wanted to add a Usage section in this README.md with instructions on how to use EspMock, but when I looked at your code, I got confused. There is an `Arduino.h` file under `src/`, but that doesn't make sense, since it would cause multiple `Arduino.h` to appear to the compiler. I think this file can be removed.

I *think* your intention was to make the EspMock library transparent, once it is included in the `ARDUINO_LIBS` variable of the EpoxyDuino's `Makefile`. I think most programs which are designed to work under both ESP32 and ESP8266 have this little bit of header file machinery:

```C++
#if defined(ESP8266)
  #include <ESP8266WiFi.h>
#elif defined(ESP32)
  #include <WiFi.h>
#else 
  #error Unsupported platform
#endif
#include <WiFiUdp.h>
...
```

When compiling such a program under EpoxyDuino, the preprocessing will fail, so I think this needs to be updated to something like this:

```C++
#if defined(ESP8266)
  #include <ESP8266WiFi.h>
#elif defined(ESP32)
  #include <WiFi.h>
#elif defined(EPOXY_DUINO)
  #include <ESP8266WiFi.h>
#else 
  #error Unsupported platform
#endif
```

It is currently not possible to tell EpoxyDuino to "compile the ESP8266 flavor of EpoxyDuino", or "compile the ESP32 flavor of EpoxyDuino". In my mind, EpoxyDuino should be considered to be a separate, independent implementation of the Arduino API. When various networking libraries are added, I think they should be self-contained within the EpoxyDuino environment. Ideally, the names of these mock libraries would not contain "ESP8266" within them, because they are targeting the EpoxyDuino environment.

On the other hand, there are certain ESP8266 libraries that you are mocking out, specifically to make sure that your programs that you wrote for ESP8266 compile properly using a Linux environment. I'm not entirely sure how to organize these libraries so that it makes sense to us, and to potential users of EspMock.

[Edit: fix typos]

**Comment by hsaturn** [comment]
Arduino.h depends of the board used, but is always included.
As this files exists in the root directory of EpoxyDuino, it cannot been overriden as EspMock requires.

I've added the correct Arduino.h for Esp8266. But still, both files are used when compiling...
This is not really a problem because the mock is not intended to build real binaries. But this could produce some false positives builds or false failed build when using pins for example (which are also platform dependent).

We have to think a little about that. I'm pretty sure that EpoxDuino.mk can easilly offer that (once Epoxy/Arduino.h is moved in a better place).

Yet, I'm busy with adding ESPAsyncTCP to the mock (because I'm adding asynchronous feature to my TinyMqtt library also).
